# Generated by Django 6.0.6 on 2026-06-27 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('RESTOCKABLE', 'Restockable'), ('DAMAGED', 'Damaged / Defective')], default='RESTOCKABLE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('RESTOCKED', 'Restocked'), ('DISCARDED', 'Discarded')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='warehouse.buyer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_returns', to='warehouse.finishedproduct')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_returns', to='warehouse.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_returns', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('return_kind', models.CharField(choices=[('RAW_CLOTH', 'Raw Cloth'), ('READYMADE', 'Readymade Items')], max_length=20)),
                ('meters_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('CONFIRMED', 'Confirmed by Supplier')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns_created', to=settings.AUTH_USER_MODEL)),
                ('raw_cloth_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to='warehouse.rawclothbatch')),
                ('readymade_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to='warehouse.readymadestock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='warehouse.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='warehouse.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
