# Generated by Django 6.0.6 on 2026-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_buyerreturn_supplierreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='alert_email',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_otp_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_name',
            field=models.CharField(default='My Garment Business', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
