# Generated by Django 6.0.6 on 2026-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_add_system_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
