# Generated by Django 6.0.6 on 2026-06-27 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_add_phone_to_warehouse_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='fcm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='firebase_service_account_json',
            field=models.TextField(blank=True, help_text='Full Firebase service account JSON string'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='wa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='wa_phone_number_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Phone Number ID', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='wa_token',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Business access token', max_length=512),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse_fcm_tokens',
            },
        ),
    ]
